### ISSUE TITLE
The new version in vscode will report an error, for example:Property 'XXXX' does not exist on type 'Vue'.Vetur(2339)

### ISSUE THREAD

**Issue by vibin-lin** [vuejs/vetur#1242]
After upgrading the new version of vetur in vscode today, every page will report an error, for example:Property 'XXXX' does not exist on type 'Vue'.Vetur(2339)
But I don't use typescript

![image](https://user-images.githubusercontent.com/20037879/56707388-2efc3700-674b-11e9-8e55-a182c5ac561a.png)

**Comment by StriveTeam** [comment]
I have the same problem and I can't fix it

**Comment by StriveTeam** [comment]
version 0.18.1 is ok

**Comment by StriveTeam** [comment]
vetur: version 0.18.1 is ok

**Comment by Louiscd** [comment]
ME TOO

**Comment by vadimjoy** [comment]
![image](https://user-images.githubusercontent.com/14856940/56711265-7979b580-6743-11e9-83a2-c33902ce16bb.png)

**Comment by OldDream** [comment]
I roll back to 0.18.1

**Comment by vadimjoy** [comment]
Thx! Rollback solves the problem11:43, 25 апреля 2019 г., OldDream <notifications@github.com>:I roll back to 0.18.1

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by caven-chen** [comment]
![image](https://user-images.githubusercontent.com/33321375/56717010-4b5d9b00-676e-11e9-8f17-1af1f0824261.png)

all pages have this problem

**Comment by AnthonyChamberlin** [comment]
yep rollback works 👍 thanks!

**Comment by topul** [comment]
I roll back to 0.18.1 too

**Comment by gunydev** [comment]
rollback to 0.18.1 it work!

**Comment by bagaskarala** [comment]
the new vetur formatting (indentation) also doesnt work well :(

otw rollback to 0.18.1

**Comment by kinesias** [comment]
temporary solution:	"vetur.experimental.templateInterpolationService": false

**Comment by jzatt** [comment]
Spend some time trying to figure out why all my .vue files where reporting (strange) errors all of the sudden. Also tried the temporary solution above... Rollback to 0.18.1 was the only thing that worked.

**Comment by aljafor** [comment]
You can also disable template formatting for HTML

**Comment by amdp** [comment]
> "vetur.experimental.templateInterpolationService": false

how do you do that?

**Comment by amdp** [comment]
"vetur.experimental.templateInterpolationService": false works!
Just go to settings and in the search box copy "vetur.experimental.templateInterpolationService": false and you will find the switch!

**Comment by stevyrino** [comment]
Having same problem on all vue components ... vetur(2304) ... property value does not exist.

**Comment by freespiriter** [comment]
Property '$route' does not exist on type 'CombinedVueInstance<Record<never, any> & Vue, object, object, object, Record<never, any>>'.Vetur(2339)
I meet the same problem.

**Comment by Smalin0020** [comment]
thinks 0.18.1 is ok!!

**Comment by GzhiYi** [comment]
回到0.18.1后再把扩展自动更新关了，等扩展后续更新吧。

**Comment by octref** [comment]
Please give a repro case. Like paste your actual code here. Not a picture.

**Comment by aphofstede** [comment]
@octref 
```
<template>
    <div :foo="bar"></div> // <- "Property 'bar' does not exist on type 'CombinedVueInstance<Vue, object, object, object, Record<never, any>>'.Vetur(2339)"
</template>

<script>
export default {
    props: {
        bar: Array,
    },
}
</script>
```

**Comment by octref** [comment]
@aphofstede Reported upstream issue https://github.com/vuejs/vue/issues/9935

In the future please create new issues instead of appending to a different issue, thanks.

**Comment by aphofstede** [comment]
Ah, I thought you specifically asked for a repro case here. Thanks for investigating! 👍

**Comment by RyannGalea** [comment]
Does anyone know why I'm having this issue with nuxt using typescript. Having issues calling methods? Works in dev but cannot build

![nuxthelp](https://user-images.githubusercontent.com/18360468/57437003-33b10700-7284-11e9-9835-997e707f95af.jpg)

**Comment by jayporta** [comment]
@RyannGalea Yes. When using Vue class components, methods go inside the class, not in the component object.

Example:

```javascript
export default YourClass extends Vue {

  toggleMenu () {
    ....
  }

  closeMenu () {
    ....
  }
}
```

**Comment by jayporta** [comment]
This is still happening even on 0.18.1. I created an interface for an object but Vetur is still displaying an error

```javascript
interface tableRow {
  name: string,
  message: string
}

interface TableData {
  columnTitles: Array<string>,
  rows: Array<TableRow>
}
```
```javascript
export default class Bookings extends Vue {
  tableData!: Array<TableData>

  mounted () {
    // error: Property 'rows' does not exist on type 'TableData[]'.Vetur(2339)
    this.tableData.rows.push({ 
       name: 'Jay',
       message: 'Using TypeScript in Vue is really frustrating' 
    })
  }
}
```

**Comment by Drumstix42** [comment]
Had to disable `vetur.experimental.templateInterpolationService` to prevent this bug from happening where something was defined under `props` but not under `data`, etc.

**Comment by rchl** [comment]
@octref This seems to still be a problem in vetur 0.22.2.

The [upstream issue](https://github.com/vuejs/vue/issues/9935) is still open and the [PR submitted upstream](https://github.com/vuejs/vue/pull/10074) was rejected with a statement that [it works in typescript >=3.5](https://github.com/vuejs/vue/pull/10074#issuecomment-526679018) anyway.

So, is vetur using old, bundled typescript ([it seems so here](https://github.com/vuejs/vetur/blob/81dcfec6a40b650a0fbeaeb83b685a0a81d3e617/server/package.json#L42))?

In SublimeText, where I'm using latest vue-language-server 0.0.60, it actually works fine, but not in vetur. In SublimeText I'm getting this info in the console:
```
lsp-vue: Loaded bundled typescript@3.6.2.
```
so the one I've installed in my project. In Vetur, I see `Loaded bundled typescript@3.3.4000.`.

So easy fix? Update bundled typescript? Or is there a way to use one from the project?

**Comment by lvaroqui** [comment]
Still have the issue with nuxt components !

**Comment by rchl** [comment]
@lvaroqui feel free to post your component somewhere for someone to look. Sometimes you need to explicitly annotate things like `head` or `computed` for this to work.

**Comment by jsuria** [comment]
Encountered this just now. Turns out the Vetur component needed to be reloaded and the error went away, but the usual notification icon on the vscode sidebar didn't display (had to check the Extensions page on a hunch). Might be a vscode bug?

**Comment by atilkan** [comment]
It does it again. Current version 0.28

**Comment by yoyo930021** [comment]
> It does it again. Current version 0.28

Please turn off `vetur.validate.template: false`.
This problem is in vue 2 libs. We can't fixed it.

**Comment by falconvk** [comment]
> > It does it again. Current version 0.28
> 
> Please turn off `vetur.validate.template: false`.
> This problem is in vue 2 libs. We can't fixed it.

What about this still happening inside the script?
Referencing any part of `data` or `methods` with `this.property` results in this error.
Do we just disable the script validation completely? 😕

**Comment by octref** [comment]
@falconvk I updated https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#property-xxx-does-not-exist-on-type-combinedvueinstance, please take a look.
