### ISSUE TITLE
format failed

### ISSUE THREAD

**Issue by Hufe921** [vuejs/vetur#3035]
- [√] I have searched through existing issues
- [√] I have read through [docs](https://vuejs.github.io/vetur)
- [√] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [√] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows 10
- Vetur version:0.34.1
- VS Code version:1.57.1

## Problem

fomat error
` Vetur initialized
[INFO ] Find node_modules paths in g:\winning\win6.0\winning-webui-outpatient-medical-record - 328ms
[INFO ] Loaded bundled typescript@4.3.2.
[INFO ] Loaded bundled prettier.
[INFO ] Loaded bundled @starptech/prettyhtml.
[INFO ] Loaded bundled prettier-eslint.
[INFO ] Loaded bundled prettier-tslint.
[INFO ] Loaded bundled stylus-supremacy.
[INFO ] Loaded bundled @prettier/plugin-pug.
Prettier format failed
[Error - 下午1:16:08] Error: Cannot find module '@umijs/fabric'
Require stack:
- g:\.prettierrc.js
- c:\Users\dell\.vscode\extensions\octref.vetur-0.34.1\server\node_modules\prettier\third-party.js
- c:\Users\dell\.vscode\extensions\octref.vetur-0.34.1\server\node_modules\prettier\index.js
- c:\Users\dell\.vscode\extensions\octref.vetur-0.34.1\server\dist\vls.js
- c:\Users\dell\.vscode\extensions\octref.vetur-0.34.1\server\dist\vueServerMain.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (g:\.prettierrc.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14) `

**Comment by triforcely** [comment]
We need a small example of how to reproduce this problem.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
cc @yoyo930021

**Comment by icebob** [comment]
Same issue here. It works with 0.33.1, but doesn't with 0.34.0 and 0.34.1
