### ISSUE TITLE
vue language server is not working in 0.9.0

### ISSUE THREAD

**Issue by ColMugX** [vuejs/vetur#323]
platform: macos 10.12
vetur: 0.9.0

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'js-beautify'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/.vscode/extensions/octref.vetur-0.9.0/client/node_modules/vue-language-server/dist/modes/style/index.js:8:23)
    at Object.<anonymous> (/Users/xxx/.vscode/extensions/octref.vetur-0.9.0/client/node_modules/vue-language-server/dist/modes/style/index.js:128:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:58y0:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Info  - 4:05:39 PM] Connection to server got closed. Server will restart.
```
i cant see more,and i see it can not work only.

**Comment by HerringtonDarkholme** [comment]
Try uninstalling and reinstalling.

Sadly, I suspect this is vscode's problem. VSCode extension usually has incomplete node_modules.

You can try inspecting node_modules in the extension folder `~/.vscode/extensions/`

**Comment by octref** [comment]
Yea, this is another one... https://github.com/vuejs/vetur/issues/268#issuecomment-310826987

Try to go `/Users/xxx/.vscode/extensions/octref.vetur-0.9.0/client` and run `npm install`.

If this works I'll look into if it's VSCode's problem.

**Comment by ColMugX** [comment]
@HerringtonDarkholme ur right

i reinstalled in last 2 hours

ty.

**Comment by octref** [comment]
I renamed the issue so it's easier to find. Hope you don't mind.

**Comment by ColMugX** [comment]
@octref  ok, make yourself.
